# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package To PyPI

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/workflows/build.yml

    - name: Pack release
      run: tar czf swcgeom-${{ github.ref }}.tgz dist/ LICENSE README.md

    - name: Create release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./swcgeom-${{ github.ref }}.tgz
        asset_name: swcgeom-${{ github.ref }}.tgz
        asset_content_type: application/gzip
